### ISSUE TITLE
Alt+Tab in "Add a server" crashes game

### ISSUE THREAD

**Issue by dsbilling** [P3D-Legacy/P3D-Legacy#42]
```
HResult=0x80004003
  Message=Objektreferanse er ikke satt til en objektforekomst.
  Source=Pokemon3D
  StackTrace:
   at P3D.PauseScreen..ctor(Screen currentScreen) in E:\Users\RTRD\Bitbucket\P3D-Legacy\P3D\Screens\MainMenu\PauseScreen.vb:line 28
   at P3D.Core.Update(GameTime gameTime) in E:\Users\RTRD\Bitbucket\P3D-Legacy\P3D\Core\Core.vb:line 154
   at P3D.GameController.Update(GameTime gameTime) in E:\Users\RTRD\Bitbucket\P3D-Legacy\P3D\Core\GameController.vb:line 99
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at MonoGame.Framework.WinFormsGameWindow.TickOnIdle(Object sender, EventArgs e)
   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at MonoGame.Framework.WinFormsGameWindow.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at P3D.Program.Main(String[] args) in E:\Users\RTRD\Bitbucket\P3D-Legacy\P3D\Core\Program.vb:line 22
```

**Comment by dsbilling** [comment]
Works fine now, possibly fixed by #33
