### ISSUE TITLE
crashes while playing version 0.58

### ISSUE THREAD

**Issue by dominater01** [P3D-Legacy/P3D-Legacy#47]
im hoping these files can show you whats wrong

http://www.mediafire.com/file/cg6xhw5t16jyb5y/0.58+Crashes.zip/file

i finished kanto so far and lost some progress going through the game but i pushed through and everything seems fine except for the crashes

im on the latest version of windows 10 x64 btw

**Comment by dsbilling** [comment]
Seems like a script issue. Copied in one of the crash logs:

```Kolben Games Crash Log V 2.4
Pokémon 3D has crashed!
// Kernel PANIC

---------------------------------------------------------------------------------

Game information:

Pokémon 3D Indev version: 0.58 (100)
Content Packs: {}
Active GameMode: Pokemon 3D
GameJolt Account: FALSE
Playing on Servers: FALSE
Game Environment: OverworldScreen
Actionscript: Type: Script; Input: trainer\sprouttower\001; Line: 1
File Validation: True
Sandboxmode: False

---------------------------------------------------------------------------------

Screen state for the current screen (OverworldScreen)

IsSurfing=False
IsRiding=False
LevelFile=violet\sprouttowerf2.dat
UsedStrength=False
EntityCount=856

---------------------------------------------------------------------------------

System specifications:

Operating system: Microsoft Windows 10 Pro [6.2.9200.0]
Core architecture: 64 Bit
System time: 9/6/2020 7:36:59 PM
System language: English (United States)(ENU) / Loaded game language: en
Decimal separator: .
Available physical memory: 8 Gigabyte
Available logical processors: 4

---------------------------------------------------------------------------------

.Net installation information:

v1.1.4322    SP0
  1033    SP0
v2.0.50727  2.0.50727.4927  SP2
v3.0  3.0.30729.4926  SP2
v3.5  3.5.30729.4926  SP1
v4  
  Client  4.8.04084
  Full  4.8.04084
v4.0  
  Client  4.0.0.0

---------------------------------------------------------------------------------

Graphics Card information:

[CardName(s): "NVIDIA GeForce GTX 1050"]
[CardRAM(s) : "2147483648"]

---------------------------------------------------------------------------------

Error information:

Message: Object reference not set to an instance of an object.
InnerException: NOTHING
BaseException: Object reference not set to an instance of an object.
HelpLink: No helplink available.
Data: Items: 0
Source: Pokemon3D
Win32 Errorcode: -1

---------------------------------------------------------------------------------

Error solution:
(The provided solution might not work for your problem)

Error ID: -1
Error Type: NaN
Error Description: The error is undocumented in the error handling system.
Error Solution: NaN

---------------------------------------------------------------------------------

CallStack: 

   at P3D.Pokemon.Generate(Int32 newLevel, Boolean SetParameters)
   at P3D.Trainer.LoadTrainer(String[] Data)
   at P3D.ScriptVersion2.ScriptCommander.DoBattle(String subClass)
   at P3D.ScriptV2.Update()
   at P3D.ActionScript.Update()
   at P3D.OverworldScreen.Update()
   at P3D.Core.Update(GameTime gameTime)
   at P3D.GameController.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at MonoGame.Framework.WinFormsGameWindow.TickOnIdle(Object sender, EventArgs e)
   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at MonoGame.Framework.WinFormsGameWindow.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at P3D.Program.Main(String[] args)

---------------------------------------------------------------------------------

Enviornment dump: 

--------------------------------------------------
Generated Fields:
--------------------------------------------------

Private _actionScript As ActionScript = P3D.ActionScript
Private _particlesTexture As Texture2D = {Name = "", Width = 64, Height = 64}
Private _trainerEncountered As Boolean = False
Private _titles As List(Of Title) = {}
Private ShowControlsDelay As Single = 8
Private _GlobalGameModeScriptStarted As Boolean = False
Private Shared _fadeColor As Color = {R:0 G:0 B:0 A:255}
Private Shared _fadeValue As Int32 = 0
Private Shared _drawRodID As Int32 = -1
Public UpdateFadeOut As Boolean = False
Public UpdateFadeIn As Boolean = False

--------------------------------------------------
Generated Property:
--------------------------------------------------

Property Titles As List(Of Title) = {}
Property ActionScript As ActionScript = P3D.ActionScript
Property TrainerEncountered As Boolean = False
Property FadeColor As Color = {R:0 G:0 B:0 A:255}
Property FadeValue As Int32 = 0
Property DrawRodID As Int32 = -1
Property GlobalGameModeScriptStarted As Boolean = False
Property PreScreen As Screen = Nothing
Property Identification As Identifications = OverworldScreen
Property MouseVisible As Boolean = False
Property CanBePaused As Boolean = True
Property CanMuteMusic As Boolean = True
Property CanChat As Boolean = True
Property CanTakeScreenshot As Boolean = True
Property CanDrawDebug As Boolean = True
Property CanGoFullscreen As Boolean = True
Property IsDrawingGradients As Boolean = False
Property IsOverlay As Boolean = False

---------------------------------------------------------------------------------

You should report this error.

Go to "http://pokemon3d.net/forum/forums/6/create-thread" to report this crash there.```

**Comment by dsbilling** [comment]
Tested on latest commit, works fine. Cannot replicate.
